name: default
channels:
    - hds.sandbox
    - conda-forge
    - nodefaults
dependencies:
    - python
    - pip:
        - zenodo-get @ git+https://github.com/hds-sandbox/zenodo_get.git@patch-1
        - cirrocumulus
